@url=http://localhost:3000/api/v1/notes


@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlYjYyYjUxNGE2ZWY2MTQ4NGY4ZjdiOSIsImlhdCI6MTU4ODk5NzQzMiwiZXhwIjoxNTg4OTk4MzMyfQ.-1lp8m-GH4oxfAik8cf9SPUAjgdFcn2faH-JIGt3zBs

@nid = 5eb62d4b7425183abc55d2fa

### Get All Notes
GET {{url}}


### Get single note
GET {{url}}/{{nid}}


### Create Note
POST {{url}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "body": "This is a body hai ta -2",
  "title": "This is a private title",
  "isPrivate": false
}


### Update Note
PATCH {{url}}/{{nid}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "body": "this is a private body from patch req ok"
}

### Delete Note
DELETE {{url}}/{{nid}}
Authorization: Bearer {{authToken}}