### Get All Notes
GET http://localhost:3000/api/v1/notes


### Get single note
GET http://localhost:3000/api/v1/notes/5eb426a1f2e80f18380ee2b7


### Create Note
POST http://localhost:3000/api/v1/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlYjUzYTlhZDI0MTg2MTlhMDU4ZmQ2YiIsImlhdCI6MTU4ODkzNTMyMiwiZXhwIjoxNTg5MDIxNzIyfQ.B1Db_wojv-dLeMdCyQ-kMOXlYcC4OPAemjQkRQDQIBI

{
  "body": "This is a body hai ta -2",
  "title": "This is a private title",
  "isPrivate": true
}


### Update Note
PATCH http://localhost:3000/api/v1/notes/5eb426a1f2e80f18380ee2b7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlYjUyOWYxMTk5YTk1MDg2Y2VhMDcxOSIsImlhdCI6MTU4ODkzMTA1NywiZXhwIjoxNTg5MDE3NDU3fQ.X6UKWPJ2nLehmqb1TLhNZoWkNDNtRDwGuriJt79mDN4

{
  "body": "this is a private body from patch req ok"
}

### Delete Note
DELETE http://localhost:3000/api/v1/notes/5eb53aadd2418619a058fd6c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlYjUzYTlhZDI0MTg2MTlhMDU4ZmQ2YiIsImlhdCI6MTU4ODkzNTMyMiwiZXhwIjoxNTg5MDIxNzIyfQ.B1Db_wojv-dLeMdCyQ-kMOXlYcC4OPAemjQkRQDQIBI