@url=http://localhost:3000/api/v1/users

@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlYjYyM2Y3MTM1YzEwMWU4YzYwNTJjZSIsImlhdCI6MTU4ODk5NTExNCwiZXhwIjoxNTg4OTk2MDE0fQ.OPzkxy2NUzG58XCNpmAvWLwZznGyDwoatg8PONe3lb8

@uid = 5eb623f7135c101e8c6052ce

### GET all users
GET {{url}}


### GET single user
GET {{url}}/{{uid}}



### Edit User
PATCH {{url}}/{{uid}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Roshan JI",
  "password": "1234567"
}


### Remove User
DELETE  {{url}}/{{uid}}
Authorization: Bearer {{authToken}}



### Me
GET {{url}}/me
Authorization: Bearer {{authToken}}

